version: "3.3"
services:
  joomla:
    image: joomla:${SOFTWARE_VERSION_TAG}
    restart: always
    ports:
      - "172.17.0.1:8080:80"
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_USER: ${JOOMLA_USER}
      JOOMLA_DB_PASSWORD: ${DATABASE_PASSWORD}
      JOOMLA_DB_NAME: ${JOOMLA_DB_NAME}
      JOOMLA_SITE_NAME: Joomla
      JOOMLA_ADMIN_USER: Root
      JOOMLA_ADMIN_USERNAME: ${ADMIN_EMAIL}
      JOOMLA_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      JOOMLA_ADMIN_EMAIL: ${ADMIN_EMAIL}
    volumes:
      - ./joomla_data:/var/www/html
    networks:
      - joomla_network
    depends_on:
      - db

  db:
    image: elestio/mysql:8.0
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${JOOMLA_DB_NAME}
      MYSQL_USER: joomla
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "172.17.0.1:3306:3306"
    networks:
      - joomla_network

  pma:
    image: elestio/phpmyadmin:latest
    restart: always
    ports:
      - "172.17.0.1:15676:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${JOOMLA_USER}
      PMA_PASSWORD: ${DATABASE_PASSWORD}
      UPLOAD_LIMIT: 500M
    networks:
      - joomla_network
    depends_on:
      - db

volumes:
  joomla_data:
  mysql:

networks:
  joomla_network:
    driver: bridge
